// Web lint = shared base + browser globals (F0.2 carry-over). The shared base only
// registers `globals.node`; App Router client components touch `window`/`document`/etc.,
// which would otherwise trip `no-undef`. Server components keep the node globals too,
// so we union both rather than split per-file.
import base from '@ffai/config/eslint';
import globals from 'globals';

export default [
  ...base,
  {
    // Generated by Next on dev/build — never our code to lint.
    ignores: ['next-env.d.ts', '.next/**'],
  },
  {
    files: ['src/**/*.{ts,tsx}', 'test/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },
];
