export const CATEGORY_ICONS = [
  'home',
  'bolt',
  'droplet',
  'flame',
  'wifi',
  'phone',
  'tool',
  'sofa',
  'wash',
  'shopping-cart',
  'restaurant',
  'coffee',
  'pizza',
  'beer',
  'car',
  'gas-station',
  'bus',
  'parking',
  'bike',
  'plane',
  'beach',
  'heartbeat',
  'pill',
  'stethoscope',
  'dental',
  'barbell',
  'shirt',
  'scissors',
  'perfume',
  'mood-smile',
  'baby-carriage',
  'school',
  'book',
  'paw',
  'gift',
  'tv',
  'movie',
  'gamepad',
  'music',
  'ticket',
  'repeat',
  'cloud',
  'laptop',
  'pig-money',
  'credit-card',
  'receipt-tax',
  'shield-check',
  'building-bank',
  'heart-handshake',
  'tag',
] as const;

export type CategoryIcon = (typeof CATEGORY_ICONS)[number];

export function isCategoryIcon(value: unknown): value is CategoryIcon {
  return typeof value === 'string' && (CATEGORY_ICONS as readonly string[]).includes(value);
}

export const CATEGORY_COLORS = [
  'scarlet',
  'vermilion',
  'orange',
  'amber',
  'gold',
  'yellow',
  'lime',
  'green',
  'emerald',
  'mint',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'orchid',
  'magenta',
  'pink',
  'rose',
  'brown',
  'graphite',
  'gray',
] as const;

export type CategoryColor = (typeof CATEGORY_COLORS)[number];

export function isCategoryColor(value: unknown): value is CategoryColor {
  return typeof value === 'string' && (CATEGORY_COLORS as readonly string[]).includes(value);
}
