import { type CategoryColor, type CategoryIcon } from '@rondo/types';
import {
  IconBabyCarriage,
  IconBarbell,
  IconBeach,
  IconBeer,
  IconBike,
  IconBolt,
  IconBook,
  IconBuildingBank,
  IconBus,
  IconCar,
  IconCloud,
  IconCoffee,
  IconCoin,
  IconCreditCard,
  IconDental,
  IconDeviceGamepad2,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDroplet,
  IconFlame,
  IconGasStation,
  IconGift,
  IconHeartHandshake,
  IconHeartbeat,
  IconHome,
  IconMoodSmile,
  IconMovie,
  IconMusic,
  IconParking,
  IconPaw,
  IconPerfume,
  IconPigMoney,
  IconPill,
  IconPizza,
  IconPlane,
  IconReceiptTax,
  IconRepeat,
  IconSchool,
  IconScissors,
  IconShieldCheck,
  IconShirt,
  IconShoppingCart,
  IconSofa,
  IconStethoscope,
  IconTag,
  IconTicket,
  IconTool,
  IconToolsKitchen2,
  IconWash,
  IconWifi,
} from '@tabler/icons-react';

import type { TablerIcon } from '@tabler/icons-react';

export interface CategoryLook {
  Icon: TablerIcon;
  color: string;
}

const ICONS: Record<CategoryIcon, TablerIcon> = {
  home: IconHome,
  bolt: IconBolt,
  droplet: IconDroplet,
  flame: IconFlame,
  wifi: IconWifi,
  phone: IconDeviceMobile,
  tool: IconTool,
  sofa: IconSofa,
  wash: IconWash,
  'shopping-cart': IconShoppingCart,
  restaurant: IconToolsKitchen2,
  coffee: IconCoffee,
  pizza: IconPizza,
  beer: IconBeer,
  car: IconCar,
  'gas-station': IconGasStation,
  bus: IconBus,
  parking: IconParking,
  bike: IconBike,
  plane: IconPlane,
  beach: IconBeach,
  heartbeat: IconHeartbeat,
  pill: IconPill,
  stethoscope: IconStethoscope,
  dental: IconDental,
  barbell: IconBarbell,
  shirt: IconShirt,
  scissors: IconScissors,
  perfume: IconPerfume,
  'mood-smile': IconMoodSmile,
  'baby-carriage': IconBabyCarriage,
  school: IconSchool,
  book: IconBook,
  paw: IconPaw,
  gift: IconGift,
  tv: IconDeviceTv,
  movie: IconMovie,
  gamepad: IconDeviceGamepad2,
  music: IconMusic,
  ticket: IconTicket,
  repeat: IconRepeat,
  cloud: IconCloud,
  laptop: IconDeviceLaptop,
  'pig-money': IconPigMoney,
  'credit-card': IconCreditCard,
  'receipt-tax': IconReceiptTax,
  'shield-check': IconShieldCheck,
  'building-bank': IconBuildingBank,
  'heart-handshake': IconHeartHandshake,
  tag: IconTag,
};

const TOKENS: Record<CategoryColor, string> = {
  scarlet: 'var(--cat-scarlet)',
  vermilion: 'var(--cat-vermilion)',
  orange: 'var(--cat-orange)',
  amber: 'var(--cat-amber)',
  gold: 'var(--cat-gold)',
  yellow: 'var(--cat-yellow)',
  lime: 'var(--cat-lime)',
  green: 'var(--cat-green)',
  emerald: 'var(--cat-emerald)',
  mint: 'var(--cat-mint)',
  teal: 'var(--cat-teal)',
  cyan: 'var(--cat-cyan)',
  sky: 'var(--cat-sky)',
  blue: 'var(--cat-blue)',
  indigo: 'var(--cat-indigo)',
  violet: 'var(--cat-violet)',
  purple: 'var(--cat-purple)',
  orchid: 'var(--cat-orchid)',
  magenta: 'var(--cat-magenta)',
  pink: 'var(--cat-pink)',
  rose: 'var(--cat-rose)',
  brown: 'var(--cat-brown)',
  graphite: 'var(--cat-graphite)',
  gray: 'var(--cat-gray)',
};

const NEUTRAL = 'var(--muted-foreground)';

export function categoryLook(icon: CategoryIcon | null, color: CategoryColor | null): CategoryLook {
  return {
    Icon: (icon === null ? undefined : ICONS[icon]) ?? IconCoin,
    color: color === null || !(color in TOKENS) ? NEUTRAL : TOKENS[color],
  };
}
